name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Initial Cleanup of Docker Environment
        run: |
          docker-compose -p atomize down || true
          docker network prune -f || true
          docker system prune -f || true  # Prunes unused resources

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Test Docker Compose Services
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker-compose -p atomize up --build -d
          docker-compose ps
          docker-compose logs

      # Final Cleanup Steps
      - name: Tear down Docker environment
        run: |
          docker-compose -p atomize down
          sleep 5  # Short delay to allow containers to stop cleanly

      - name: Forcefully Remove Docker Network
        run: |
          docker network disconnect -f atomize_default $(docker ps -aq) || true
          docker network rm atomize_default || true

      - name: Prune Docker System (optional)
        run: docker system prune -f

