name: Deploy to Azure App Services

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    name: Deploy Microservices to Azure
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - characters
          - introduction
          - sentiments
          - themeservice
          - streamlit_ui

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy ${{ matrix.service }} Service to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ matrix.service }}
        publish-profile: ${{ secrets['AZURE_PUBLISH_PROFILE_' + matrix.service | upper] }}
        package: .
