name: Build, Push Docker Images, and Update SwaggerHub

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build and Push Docker Images to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - characters_service
          - introduction_service
          - sentiment_service
          - theme_service
          - user_data_service
          - streamlit_ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push ${{ matrix.service }} Image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: derricknarkah/${{ matrix.service }}:latest
        build-args: |
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    # Add SwaggerHub CLI steps after Docker image builds
    - name: Install SwaggerHub CLI
      run: npm install -g swaggerhub-cli

    - name: Update SwaggerHub API Documentation
      run: swaggerhub api:update DERRICKNARKAH_1/atomizeAPI/1.0.0 -f unified_openapi.yaml
      env:
        SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
