name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - characters_service
          - introduction_service
          - sentiments_service
          - theme_service
          - streamlit_ui

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push ${{ matrix.service }} Image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: derricknarkah/${{ matrix.service }}:latest
        build-args: |
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
